verbose: true
base_link: base_link
models:
 - name: arm
   type: chain
   frame: wrist_roll_link
 - name: camera
   type: camera3d
   frame: head_camera_rgb_optical_frame
   topic: /head_camera/depth_registered/points
free_params:
 - shoulder_pan_joint
 - shoulder_lift_joint
 - upperarm_roll_joint
 - elbow_flex_joint
 - forearm_roll_joint
 - wrist_flex_joint
 - wrist_roll_joint
 - head_tilt_joint
 - camera_fx
 - camera_fy
 - camera_cx
 - camera_cy
 - camera_z_offset
 - camera_z_scaling
free_frames:
 - name: head_camera_rgb_joint
   x: true
   y: true
   z: true
   roll: true
   pitch: false
   yaw: true
 - name: head_pan_joint
   x: true
   y: true
   z: true
   roll: true
   pitch: true
   yaw: true
 - name: checkerboard
   x: true
   y: false
   z: true
   roll: false
   pitch: true
   yaw: false
error_blocks:
 - name: hand_eye
   type: chain3d_to_chain3d
   model_a: camera
   model_b: arm
 - name: ground_plane
   type: chain3d_to_plane
   model_a: camera
   a: 0.0
   b: 0.0
   c: 1.0
   d: 0.0
   scale: 1.0
 - name: restrict_camera
   type: outrageous
   param: head_camera_rgb_joint
   joint_scale: 0.0
   position_scale: 0.1
   rotation_scale: 0.1
